docs/AboutUs.md, docs/team/yugan01.md
=> Update AboutUs page about Yugan's info

docs/AboutUs.md, docs/team/dinesh.md
=> Update AboutUs page with Dinesh's info

docs/AboutUs.md, docs/team/jolynleow.md
=> Update AboutUs page with Jolyn's info

docs/AboutUs.md, docs/team/yuanchengg.md
=> Update Yuan Cheng's AboutUs

docs/DeveloperGuide.md
=> Add use cases to developer guide

docs/DeveloperGuide.md
=> Update DG with target user profile, value propositions and user stories

docs/DeveloperGuide.md
=> Add Glossary

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/parser/DeleteCommandParser.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
=> Add deleteCommand class

src/main/java/seedu/address/model/healthservice/Healthservice.java, src/main/java/seedu/address/model/person/Birthdate.java, src/main/java/seedu/address/model/person/Nric.java, src/main/java/seedu/address/model/person/Sex.java
=> Add new files for AddCommand

src/main/java/seedu/address/ui/HelpWindow.java, src/main/resources/view/HelpWindow.css, src/main/resources/view/HelpWindow.fxml
=> Update Help Command Window

src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/TypicalPersons.java
Fixes #62 
Test files for 
1. AddCommandTest.java
2. CommandTestUtil.java
3. EditCommandTest.java
4. EditPersonDescriptorTest.java
5. EditCommandParserTest.java (incomplete)
6. EditPersonDescriptorBuilder.java
7. PersonBuilder.java
8. TypicalPersons.java
=> Update Test files

src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/healthservice/HealthService.java, src/main/java/seedu/address/model/person/Birthdate.java, src/main/java/seedu/address/model/person/Nric.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/Sex.java, src/main/java/seedu/address/ui/PersonCard.java
Fixes #71 
Add validation checks for NRIC, Sex, Birthdates and HealthService fields in Add Command
=> Add validation checks

src/main/java/seedu/address/logic/parser/AddFCommandParser.java, src/test/java/seedu/address/logic/commands/HelpCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
=> Update and add Tests for HelpCommand feature

src/main/java/seedu/address/logic/commands/CommandKeywords.java
=> Fix HelpCommand with keyword bug

src/main/java/seedu/address/model/person/Birthdate.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/model/person/UniquePersonListTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/PersonUtil.java
=> Update fields in test classes

src/main/java/seedu/address/logic/commands/AddFCommand.java, src/main/java/seedu/address/model/person/Birthdate.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java
=> Fix issue with loading from existing data

src/main/java/seedu/address/ui/HelpKeywordWindow.java
=> Update command details for HelpCommand Appt

src/main/java/seedu/address/logic/commands/ApptCommand.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/ui/PersonCard.java
=> Edit ApptCommand feature to display text for no appointments 

src/main/java/seedu/address/logic/commands/HelpCommand.java
=> Add equals() method to HelpCommand

src/main/java/seedu/address/logic/commands/CommandResult.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> Fix test cases

src/main/java/seedu/address/logic/parser/ApptCommandParser.java, src/main/java/seedu/address/model/ApptSorter.java, src/main/java/seedu/address/model/person/Appt.java, src/main/java/seedu/address/model/person/Person.java
=> Update Appt Command to sort appointment date and time

src/main/java/seedu/address/model/healthservice/HealthService.java, src/main/java/seedu/address/model/person/Birthdate.java, src/main/java/seedu/address/model/person/Nric.java, src/main/java/seedu/address/model/person/Sex.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
=> Add check argument functionality

src/main/java/seedu/address/model/healthservice/HealthService.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/testutil/TypicalPersons.java
Blood Test, Cancer Screening, vaccination and Consult are the healthservices that the user can choose from.
Fixes #118
=> Add fixed healthservices to be provided

src/main/java/seedu/address/logic/commands/ViewCommand.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/ui/HelpKeywordWindow.java, src/main/java/seedu/address/ui/HelpWindow.java, src/main/java/seedu/address/ui/UiPart.java
=> Add help text for view and filter commands

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/DeleteApptCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/DeleteApptCommandParser.java, src/main/java/seedu/address/model/person/Person.java
=> Add DeleteApptCommand feature

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddFCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/patient/Patient.java, src/main/java/seedu/address/storage/JsonAdaptedAllergy.java, src/main/java/seedu/address/storage/JsonAdaptedPatient.java, src/main/java/seedu/address/ui/PatientInfoPanel.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java, src/test/java/seedu/address/testutil/PatientBuilder.java
=> Change allergies to a list

.vscode/settings.json, src/main/java/seedu/address/logic/commands/ViewCommand.java
=> Add assertions to view command

src/main/java/seedu/address/logic/commands/CommandKeywords.java, src/main/java/seedu/address/model/patient/Patient.java
=> Fix broken ui and help command bug

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/model/patient/Patient.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java, src/test/java/seedu/address/testutil/PatientBuilder.java
=> Remove appointment field from EditCommand

src/main/resources/view/PatientInfoPanel.fxml
=> Add resizable property to scrollpane for ViewCommand UI

src/main/java/seedu/address/logic/parser/AddFCommandParser.java, src/main/java/seedu/address/logic/parser/ViewCommandParser.java
=> Add error handling for ViewCommand

src/main/java/seedu/address/logic/commands/ApptCommand.java, src/main/java/seedu/address/logic/parser/ApptCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/healthservice/HealthService.java, src/main/java/seedu/address/model/patient/Appt.java, src/main/java/seedu/address/storage/JsonAdaptedAppt.java, src/main/java/seedu/address/storage/JsonAdaptedPatient.java, src/test/java/seedu/address/testutil/PatientBuilder.java
=> Add health service in ApptCommand

src/main/java/seedu/address/logic/commands/CommandKeywords.java, src/main/java/seedu/address/ui/HelpKeywordWindow.java, src/main/java/seedu/address/ui/HelpWindow.java, src/main/resources/view/HelpKeywordWindow.css, src/main/resources/view/HelpKeywordWindow.fxml, src/main/resources/view/HelpWindow.css, src/main/resources/view/HelpWindow.fxml
Closes #167 
Improve UI of HelpWindow
Adds a scroll pane into HelpKeywordWindow
Adds all new commands into HelpWindow
Adds descriptions and usages of each command into the individual help window
=> Update help command include new commands

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/AddFCommand.java, src/main/java/seedu/address/logic/commands/ApptCommand.java, src/main/java/seedu/address/logic/commands/DeleteApptCommand.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/FilterCommand.java, src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/logic/commands/ViewCommand.java
=> Update MESSAGE_USAGE for all commands

src/main/java/seedu/address/logic/commands/CommandKeywords.java, src/main/java/seedu/address/logic/commands/FilterCommand.java, src/main/java/seedu/address/logic/commands/HomeCommand.java, src/main/java/seedu/address/logic/commands/ViewCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/HomeCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
=> Change ListCommand to HomeCommand

src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/ui/HelpKeywordWindow.java
=> Change prefix existing conditions

src/main/java/seedu/address/logic/commands/ViewCommand.java, src/test/java/seedu/address/logic/commands/ViewCommandTest.java
=> Add ViewCommand testcases

src/main/java/seedu/address/logic/commands/ApptCommand.java, src/main/java/seedu/address/logic/parser/DeleteApptCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/patient/Appt.java, src/main/java/seedu/address/storage/JsonAdaptedAppt.java, src/main/java/seedu/address/storage/JsonAdaptedPatient.java
=> Fix bug in ApptCommand

src/main/java/seedu/address/logic/commands/BookApptCommand.java, src/main/java/seedu/address/logic/commands/DeleteApptCommand.java, src/main/java/seedu/address/logic/parser/BookApptCommandParser.java, src/main/java/seedu/address/logic/parser/ClinicConnectSystemParser.java, src/main/java/seedu/address/logic/parser/DeleteApptCommandParser.java, src/main/java/seedu/address/model/patient/Appt.java
=> Update bookappt and deleteappt commands

src/main/java/seedu/address/model/patient/Patient.java, src/main/java/seedu/address/ui/PatientCard.java
=> Update UI to show at most 2 appointments per patient

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/AddFCommand.java, src/main/java/seedu/address/logic/commands/CommandResult.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/AddFCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/patient/Patient.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPatient.java, src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java, src/test/java/seedu/address/logic/commands/CommandResultTest.java, src/test/java/seedu/address/logic/commands/ViewCommandTest.java
=> Change required fields for add and addf

src/main/java/seedu/address/model/patient/Patient.java, src/test/java/seedu/address/logic/commands/AddFCommandIntegrationTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddFCommandParserTest.java, src/test/java/seedu/address/testutil/PatientBuilder.java, src/test/java/seedu/address/testutil/TypicalPatients.java
=> Add test cases for addf command

src/main/java/seedu/address/logic/commands/FilterCommand.java, src/main/java/seedu/address/logic/parser/FilterCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/appointmentdatefilter/AppointmentDateFilter.java
=> Fix endDate bug for filter commands

src/main/java/seedu/address/logic/commands/CommandKeywords.java, src/test/java/seedu/address/logic/commands/HelpCommandTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
=> Add HelpCommand testcases

src/main/java/seedu/address/ui/PatientInfoPanel.java, src/main/resources/view/PatientInfoPanel.fxml
=> Improve ViewCommand Ui

src/main/java/seedu/address/model/patient/ApptList.java, src/main/java/seedu/address/model/patient/Patient.java, src/main/java/seedu/address/ui/PatientCard.java
=> Update appt commands to improve abstraction

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/model/patient/AllergyList.java, src/main/java/seedu/address/model/patient/Patient.java, src/main/java/seedu/address/model/patient/exceptions/AllergyAlreadyExistsException.java, src/main/java/seedu/address/model/patient/exceptions/AllergyNotFoundException.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/parser/AddFCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java, src/test/java/seedu/address/testutil/PatientBuilder.java, src/test/java/seedu/address/testutil/TypicalPatients.java
=> Update editcommand allergies

src/main/java/seedu/address/ui/HelpKeywordWindow.java
=> Update EditCommand HelpKeywordWindow

docs/index.md
=> Edit landing page file

src/main/java/seedu/address/ui/PatientCard.java, src/main/resources/view/MainWindow.fxml, src/main/resources/view/PatientListCard.fxml
=> Update ui to show healthservice for appt

src/main/java/seedu/address/logic/commands/FilterCommand.java, src/main/java/seedu/address/logic/commands/commandresult/CommandResult.java, src/main/java/seedu/address/logic/commands/commandresult/DefaultCommandResult.java, src/main/java/seedu/address/logic/commands/commandresult/ExitCommandResult.java, src/main/java/seedu/address/logic/commands/commandresult/KeywordCommandResult.java, src/main/java/seedu/address/logic/commands/commandresult/ShowFilteredApptsCommandResult.java, src/main/java/seedu/address/logic/commands/commandresult/ShowPatientInfoCommandResult.java, src/main/java/seedu/address/ui/MainWindow.java, src/test/java/seedu/address/logic/commands/CommandResultTest.java, src/test/java/seedu/address/logic/commands/FilterCommandTest.java
=> Change filter command implementation

src/main/java/seedu/address/model/patient/Appt.java
=> Fix bug in duplicate appointment handling

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/DeleteApptCommand.java, src/test/java/seedu/address/model/filteredappointment/FilteredAppointmentTest.java
=> Fix bug errors in deleteapptcommand

src/main/resources/view/PatientInfoPanel.fxml
=> Fix appointment field cutoff in viewUI

src/main/java/seedu/address/logic/commands/BookApptCommand.java, src/main/java/seedu/address/model/patient/Appt.java
=> Branch update book appt

src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/Prefix.java
=> Change prefix "/" symbol to "|" symbol

src/main/java/seedu/address/logic/commands/BookApptCommand.java
=> Fix bug in local date time in bookappt

src/main/java/seedu/address/logic/parser/EditCommandParser.java
=> Allow capitalisation for commands

src/main/java/seedu/address/model/patient/HealthRisk.java
=> Fix healthrisk to allow lower case

src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/AddFCommandParser.java, src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java, src/main/java/seedu/address/logic/parser/BookApptCommandParser.java, src/main/java/seedu/address/logic/parser/DeleteApptCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/FilterCommandParser.java, src/main/java/seedu/address/model/patient/BloodType.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddFCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
=> Check prefix validity

docs/UserGuide.md
=> Fix formatting for code and remove list command

docs/UserGuide.md
=> Update format of examples

src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/BookApptCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteApptCommandTest.java, src/test/java/seedu/address/logic/parser/BookApptCommandParserTest.java, src/test/java/seedu/address/logic/parser/DeleteApptCommandParserTest.java
=> Add test cases for bookappt and deleteappt commands and parsers

docs/UserGuide.md, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/appointmentdatefilter/AppointmentDateFilter.java, src/main/java/seedu/address/model/patient/Appt.java, src/main/java/seedu/address/model/patient/Birthdate.java, src/main/java/seedu/address/storage/JsonAdaptedAppt.java
=> Update bookappt to fix bugs on edge cases

docs/UserGuide.md
Fixes #384 
Fixes #325 
Fixes #317 
Fixes #300
=> Add table of contents and fix quick start

docs/_sass/minima/_base.scss
=> Change header to ClinicConnect

docs/UserGuide.md
Fixes #386 
Fixes #355 
Fixes #310 
Fixes #305
=> Add known issues to ug

docs/UserGuide.md
=> FIx user guide

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/HomeCommand.java, src/main/java/seedu/address/model/patient/Nric.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/HomeCommandTest.java
=> Fix typo based on number of patients present

docs/DeveloperGuide.md
=> Change format for add a patient mss

docs/DeveloperGuide.md
=> Add mss for edit a patient

docs/DeveloperGuide.md
=> Add mss for return to homepage
